name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel invoke coveralls
    - name: Install package and dependencies
      run: |
        invoke install
    - name: Run test suites, type checks, and linters
      run: |
        invoke validate
    - name: Report test coverage to Coveralls
      if: success()
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        coveralls --service=github

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel invoke
    - name: Build the Sphinx documentation
      run: |
        invoke install doc.install doc.build
