name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.8
          3.9
          3.10
          3.11
          3.12
    - name: Install build tools
      run: |
        python -m pip install hatch
    - name: Run test suites, type checks, and linters
      run: |
        hatch run all:check
      env:
        PYTEST_ADDOPTS: ${{ runner.os != 'Linux' && '--no-cov' || '' }}
